version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: octii
      POSTGRES_USER: octii
      POSTGRES_DB: octii
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pushpin:
    image: fanout/pushpin
    volumes:
      - pushpin:/etc/pushpin
    ports:
      - 7999:7999
  gateway:
    image: registry.innatical.com/project-neko/client-gateway:latest
    volumes:
      - ./config.lua:/usr/src/app/config.lua
      - keys:/usr/src/app/keys
    depends_on:
      - postgres
volumes:
  postgres_data:
  keys:
  pushpin:
