version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: neko
      POSTGRES_USER: neko
      POSTGRES_DB: neko
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      # If you ever need to access the DB from an external tool
      - 5432:5432
  pushpin:
    image: fanout/pushpin
    volumes:
      - ./pushpin:/etc/pushpin
    ports:
      - 7999:7999
  gateway:
    build: .
    volumes:
      - ./keys:/usr/src/app/keys
    depends_on:
      - postgres
    environment:
      - ENVIROMENT=development
volumes:
  postgres_data:
