[package]
name = "client-gatway"
version = "0.1.0"
[dependencies]
mm = "1.2.0-1"
lua-resty-http = "0.15-0"
inspect = "3.1.1-0"
lua-cjson = "2.1.0.6-1"
lua-resty-jwt = "0.2.2-0"
lapis = "1.8.2-2"
argon2-ffi = "3.0.1-1"
lua = "5.1"
lua-resty-uuid = "1.1-1"
luaossl = "20200709-0"
array = "1.3.3-0"
[scripts]
start = "lapis server"