[dependencies]
luaossl = "20200709-0"
lua-resty-http = "0.15-0"
argon2-ffi = "3.0.1-1"
array = "1.3.3-0"
lapis = "1.8.2-2"
penlight = "0.8-1"
mm = "1.2.0-1"
lua-resty-nanoid = "0.0.1-2"
lua-cjson = "2.1.0.6-1"
lua-resty-jit-uuid = "0.0.7-2"
lua-resty-jwt = "0.2.2-0"
tableshape = "2.2.0-1"
inspect = "3.1.1-0"
[package]
lua = "5.1"
version = "0.1.0"
name = "client-gatway"
[scripts]
dev = "nodemon --exec 'docker-compose up --build' -e lua"
start = "lapis server"