worker_processes ${{NUM_WORKERS}};
error_log stderr notice;
daemon off;
pid logs/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include mime.types;

  server {
    listen ${{PORT}};
    lua_code_cache ${{CODE_CACHE}};
    resolver ${{RESOLVER}};

    lua_ssl_trusted_certificate ${{SSL_CERTIFICATE}};

    client_body_temp_path temp/nginx-client-body;
    proxy_temp_path temp/nginx-proxy;
    fastcgi_temp_path temp/nginx-fastcgi;
    uwsgi_temp_path temp/nginx-uwsgi;
    scgi_temp_path temp/nginx-scgi;

    location / {
      default_type text/html;
      content_by_lua_block {
        require("lapis").serve("app")
      }
    }

    location /static/ {
      alias static/;
    }

    location /favicon.ico {
      alias static/favicon.ico;
    }
  }
}
